"""empty message

Revision ID: 2bedcf30e301
Revises: 53f432746f4a
Create Date: 2014-08-12 11:11:22.835029

"""

# revision identifiers, used by Alembic.
revision = '2bedcf30e301'
down_revision = '53f432746f4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('enabled', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_enabled')
    op.drop_column('accounts', 'enabled_at')
    ### end Alembic commands ###
