"""empty message

Revision ID: 53f432746f4a
Revises: 28fed97b29ba
Create Date: 2014-08-12 04:47:31.191523

"""

# revision identifiers, used by Alembic.
revision = '53f432746f4a'
down_revision = '28fed97b29ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('activation_code', sa.String(255), server_default='', nullable=False))
    op.add_column('accounts', sa.Column('activation_code_generated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'activation_code_generated_at')
    op.drop_column('accounts', 'activation_code')
    ### end Alembic commands ###
